stages:
  - lint
  - build
  - test
  - build-review
  - review
  - release

# CHANGE ME!
variables:
  AUTHPASSWORD: "example" # change to "" (empty string) to disable authentication
  # username is always "review" (without quotes)
  CI_REF: &ref c90f58d3aa7f030bbe0f90b4d71db25ded2fde92

include:
  # VARIABLES
  # https://git.dbogatov.org/templates/ci-snippets/-/blob/master/latex-report/variables.yml
  - project: "templates/ci-snippets"
    file: "latex-report/variables.yml"
    ref: *ref

  # LINT
  # https://git.dbogatov.org/templates/ci-snippets/-/blob/master/latex/chktex.yml
  - project: "templates/ci-snippets"
    file: "latex/chktex.yml"
    ref: *ref

  # https://git.dbogatov.org/templates/ci-snippets/-/blob/master/latex/cspell.yml
  - project: "templates/ci-snippets"
    file: "latex/cspell.yml"
    ref: *ref

  # https://git.dbogatov.org/templates/ci-snippets/-/blob/master/latex-report/metrics.yml
  - project: "templates/ci-snippets"
    file: "latex-report/metrics.yml"
    ref: *ref

  # BUILD
  # https://git.dbogatov.org/templates/ci-snippets/-/blob/master/latex/build.yml
  - project: "templates/ci-snippets"
    file: "latex/build.yml"
    ref: *ref

  # TEST
  # https://git.dbogatov.org/templates/ci-snippets/-/blob/master/latex-report/embedded-fonts.yml
  - project: "templates/ci-snippets"
    file: "latex-report/embedded-fonts.yml"
    ref: *ref

  # https://git.dbogatov.org/templates/ci-snippets/-/blob/master/latex-report/check-links.yml
  - project: "templates/ci-snippets"
    file: "latex-report/check-links.yml"
    ref: *ref

  # BUILD REVIEW
  # https://git.dbogatov.org/templates/ci-snippets/-/blob/master/latex-review-apps/build-review.yml
  - project: "templates/ci-snippets"
    file: "latex-review-apps/build-review.yml"
    ref: *ref

  # REVIEW
  # https://git.dbogatov.org/templates/ci-snippets/-/blob/master/latex-review-apps/review.yml
  - project: "templates/ci-snippets"
    file: "latex-review-apps/review.yml"
    ref: *ref

  # https://git.dbogatov.org/templates/ci-snippets/-/blob/master/latex-review-apps/stop-review.yml
  - project: "templates/ci-snippets"
    file: "latex-review-apps/stop-review.yml"
    ref: *ref

  # RELEASE
  # https://git.dbogatov.org/templates/ci-snippets/-/blob/master/latex/artifacts.yml
  - project: "templates/ci-snippets"
    file: "latex/artifacts.yml"
    ref: *ref

  # https://git.dbogatov.org/templates/ci-snippets/-/blob/master/latex/pages.yml
  - project: "templates/ci-snippets"
    file: "latex/pages.yml"
    ref: *ref

# ADJUSTMENTS

build-review:
  except: []

review:
  except: []

stop_review:
  except: []

build:
  script:
    - $LATEX_BUILD/build.sh
    - $LATEX_BUILD/build.sh -n
